exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules
  - bower_components
  - build
  - dist
permalink: /:title
timezone: null
lsi: false
markdown: kramdown
kramdown:
  auto_ids: false
  parse_block_html: true
sass:
  style: compressed
compress_html:
  startings: []
  endings: []
  clippings: all
  comments: ["<!-- ", " -->"]
  blanklines: false
  profile: false

title: Streamlink Twitch GUI
description: A multi platform Twitch.tv browser for Streamlink
keywords: Streamlink, Twitch, GUI, Streaming, Livestreamer, desktop app, web app, nw.js
baseurl: /streamlink-twitch-gui
source_link: https://github.com/streamlink/streamlink-twitch-gui
repository: streamlink/streamlink-twitch-gui

colors:
  purple: "#6441a5"
  blue: "#4869a5"
  green: "#699155"
  red: "#984155"

preview:
  - https://user-images.githubusercontent.com/467294/32060296-a08d7b44-ba6e-11e7-9793-8ef60fc3e1f0.jpg
  - https://user-images.githubusercontent.com/467294/28097571-3415adda-66b1-11e7-86dd-6aac8f41f91f.jpg
  - https://user-images.githubusercontent.com/467294/28097572-3415f4a2-66b1-11e7-9eeb-20b21b2ac6a7.jpg
